chocolate_shop/chocolate_app/urls.py
from django.urls import path
from . import views
app_name='chocolate_app'

urlpatterns = [
    path('',views.home,name='home'),
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('shop',views.shop,name='shop'),
    path('confirm', views.confirm, name='confirm'),

]

chocolate_shop/chocolate_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('chocolate_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

chocolate_shop/chocolate_app/models.py
from django.db import models

# Create your models here.
class Customer_details(models.Model):
    customer_name=models.CharField(max_length=250)
    phone_no=models.CharField(max_length=250)
    email=models.EmailField(max_length=250)
    address = models.TextField()
    district = models.CharField(max_length=250)
    city = models.CharField(max_length=250)
    chocolate = models.CharField(max_length=250)
    price = models.CharField(max_length=250)
    quantity = models.IntegerField()

    def __str__(self):
        return '{}'.format(self.customer_name)

chocolate_shop/chocolate_app/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .models import Customer_details

# Create your views here.
def home(request):
    return render(request,'home.html')


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        cpassword = request.POST['cpassword']

        if password==cpassword:
            if User.objects.filter(username=username).exists():
                messages.info(request,"username already used")
                return redirect('chocolate_app:register')
            else:
                user=User.objects.create_user(username=username,password=password)
                user.save();
                return redirect('chocolate_app:login')

        else:
            messages.info(request,"password doesn't match")
            return redirect('chocolate_app:register')


    return render(request,'register.html')


def login(request):
    if request.method == 'POST':
        username=request.POST['username']
        password = request.POST['password']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('chocolate_app:shop')
        else:
            messages.info(request,"invalid username or password")
            return redirect('chocolate_app:login')
    return render(request,'login.html')


def logout(request):
    auth.logout(request)
    return redirect('chocolate_app:home')

def shop(request):
    return render(request,'shop.html')


def confirm(request):
    if request.method == 'POST':
        customer_name=request.POST['customer_name']
        phone_no = request.POST['phone_no']
        email = request.POST['email']
        address = request.POST['address']
        district = request.POST['district']
        city = request.POST['city']
        chocolate = request.POST['chocolate']
        price = request.POST['price']
        quantity = request.POST['quantity']
        data=Customer_details(customer_name=customer_name,phone_no=phone_no,email=email,address=address,district=district,city=city,chocolate=chocolate,price=price,quantity=quantity)
        data.save();
        if data:
            messages.info(request,"success")
    return render(request,'confirm.html')

chocolate_shop/templates/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirm</title>
<style>
body{
  font-family: Calibri, Helvetica, sans-serif;
}
.container {
    padding: 50px;
    background-color: grey;
    width:300px;
    margin:80px;
}

input[type=text], input[type=email], input[type=number]{
  width: 300px;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}
select{
  width: 130px;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;

 }
input[type=text]:focus, input[type=email], input[type=number], select:focus {
  outline: none;
}
 div {
            padding: 10px 0;
         }
.registerbtn {
  background-color:  #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 125px;
  opacity: 0.9;
}
.registerbtn:hover {
  opacity: 1;
}

</style>
</head>
<body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <form method="post" action="{% url 'chocolate_app:confirm' %}">
        {% csrf_token %}

        <center>
        <div class="container">
            <h3>Please fill out these fields to confirm your order</h3>
            <input type="text" name="customer_name" placeholder= "Customer Name" size="15" required /><br>
            <input type="text" name="phone_no" placeholder="Phone Number" size="15" required /><br>
            <input type="email" name="email" placeholder="Email" size="15"required /><br>
            <input type="text" name="address" placeholder="Address" size="15"required /><br>
            <select id="inputDistrict" name="district" required>
                <option value="">Select District</option>
                <option value="Kannur">Kannur</option>
                <option value="Kozhikode">Kozhikode</option>
                <option value="Kochi">Kochi</option>
                <option value="Kasaragode">Kasaragode</option>
            </select>
            <select id="inputCity" name="city" required>
                <option value="">Select City</option>
            </select>
            <select id="chocolatename" name="chocolate" required>
                <option value="">Select Chocolate</option>
                <option value="Snickers">Snickers</option>
                <option value="Munch">Munch</option>
                <option value="Kitkat">Kitkat</option>
            </select>
            <select id="price" name="price" required>
                <option value="">Price</option>
            </select>
            <input type="number" name="quantity" placeholder="Quantity" size="15"required /><br>
            <input type="reset" class="registerbtn" value="Reset">
            <input type="submit" class="registerbtn" value="Confirm"><br><br>
            <a href="{% url 'chocolate_app:logout' %}" style="color:black;">Logout</a>
        </div>
        </center>
    </form>
    <script>
        var Kannur = ["Payyanur","Thalipparamba","Caltex",];
        var  Kozhikode= ["Vadakara", "Koyilandy", "Thamarassery"];
        var  Kochi= ["Kochi", "Aluva", "Angamali"];
        var  Kasaragode= ["Cheruvathur","Kanhangad","Neleswaram"];
        $("#inputDistrict").change(function () {
               var StateSelected = $(this).val();
               var optionsList;
               var htmlString = "";

              switch (StateSelected) {
              case "Kannur":
                optionsList = Kannur;
                break;
              case "Kochi":
                optionsList = Kochi;
                break;
              case "Kasaragode":
                optionsList = Kasaragode;
                break;
              case "Kozhikode":
                optionsList = Kozhikode;
                break;
              }

              for (var i = 0; i < optionsList.length; i++) {
                htmlString =
                htmlString +
                "<option value='" +
                optionsList[i] +
                "'>" +
                optionsList[i] +
                "</option>";
              }
              $("#inputCity").html(htmlString);
        });
    </script>
    <script>
        var Snickers = ["40","20","60",];
        var  Munch= ["10", "20", "5"];
        var  Kitkat= ["100","50","120"];
        $("#chocolatename").change(function () {
               var StateSelected = $(this).val();
               var optionsList;
               var htmlString = "";

              switch (StateSelected) {
              case "Snickers":
                optionsList = Snickers;
                break;
              case "Munch":
                optionsList = Munch;
                break;
              case "Kitkat":
                optionsList = Kitkat;
                break;
              }

              for (var i = 0; i < optionsList.length; i++) {
                htmlString =
                htmlString +
                "<option value='" +
                optionsList[i] +
                "'>" +
                optionsList[i] +
                "</option>";
              }
              $("#price").html(htmlString);
        });
    </script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
                {% if messages %}
                swal({
                    title:"Success",
                    text:"Order Placed",
                    icon:"success",
                }).then(function(){
                    window.location="{% url 'chocolate_app:shop' %}";
                {% endif %}
               });
         });
    </script>
</body>
</html>

chocolate_shop/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirm</title>
<style>


* {
  font-family: Open Sans;
}

section {
  width: 100%;
  display: inline-block;
  background: #333;
  height: 50vh;
  text-align: center;
  font-size: 22px;
  font-weight: 700;
  text-decoration: underline;
}

.footer-distributed{
	background: #666;
	box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.12);
	box-sizing: border-box;
	width: 100%;
	text-align: left;
	font: bold 16px sans-serif;
	padding: 55px 50px;
}

.footer-distributed .footer-left,
.footer-distributed .footer-center,
.footer-distributed .footer-right{
	display: inline-block;
	vertical-align: top;
}

/* Footer left */

.footer-distributed .footer-left{
	width: 40%;
}

/* The company logo */

.footer-distributed h3{
	color:  #ffffff;
	font: normal 36px 'Open Sans', cursive;
	margin: 0;
}

.footer-distributed h3 span{
	color:  lightseagreen;
}

/* Footer links */

.footer-distributed .footer-links{
	color:  #ffffff;
	margin: 20px 0 12px;
	padding: 0;
}

.footer-distributed .footer-links a{
	display:inline-block;
	line-height: 1.8;
  font-weight:400;
	text-decoration: none;
	color:  inherit;
}

.footer-distributed .footer-company-name{
	color:  #222;
	font-size: 14px;
	font-weight: normal;
	margin: 0;
}

/* Footer Center */

.footer-distributed .footer-center{
	width: 35%;
}

.footer-distributed .footer-center i{
	background-color:  #33383b;
	color: #ffffff;
	font-size: 25px;
	width: 38px;
	height: 38px;
	border-radius: 50%;
	text-align: center;
	line-height: 42px;
	margin: 10px 15px;
	vertical-align: middle;
}

.footer-distributed .footer-center i.fa-envelope{
	font-size: 17px;
	line-height: 38px;
}

.footer-distributed .footer-center p{
	display: inline-block;
	color: #ffffff;
  font-weight:400;
	vertical-align: middle;
	margin:0;
}

.footer-distributed .footer-center p span{
	display:block;
	font-weight: normal;
	font-size:14px;
	line-height:2;
}

.footer-distributed .footer-center p a{
	color:  lightseagreen;
	text-decoration: none;;
}

.footer-distributed .footer-links a:before {
  content: "|";
  font-weight:300;
  font-size: 20px;
  left: 0;
  color: #fff;
  display: inline-block;
  padding-right: 5px;
}

.footer-distributed .footer-links .link-1:before {
  content: none;
}

/* Footer Right */

.footer-distributed .footer-right{
	width: 20%;
}

.footer-distributed .footer-company-about{
	line-height: 20px;
	color:  #92999f;
	font-size: 13px;
	font-weight: normal;
	margin: 0;
}

.footer-distributed .footer-company-about span{
	display: block;
	color:  #ffffff;
	font-size: 14px;
	font-weight: bold;
	margin-bottom: 20px;
}

.footer-distributed .footer-icons{
	margin-top: 25px;
}

.footer-distributed .footer-icons a{
	display: inline-block;
	width: 35px;
	height: 35px;
	cursor: pointer;
	background-color:;
	border-radius: 2px;

	font-size: 20px;
	color: #ffffff;
	text-align: center;
	line-height: 35px;

	margin-right: 3px;
	margin-bottom: 5px;
}

/* If you don't want the footer to be responsive, remove these media queries */

@media (max-width: 880px) {

	.footer-distributed{
		font: bold 14px sans-serif;
	}

	.footer-distributed .footer-left,
	.footer-distributed .footer-center,
	.footer-distributed .footer-right{
		display: block;
		width: 100%;
		margin-bottom: 40px;
		text-align: center;
	}

	.footer-distributed .footer-center i{
		margin-left: 0;
	}

}
</style>
</head>


<footer class="footer-distributed">

			<div class="footer-left">



				<p class="footer-links">
					<a href="#" class="link-1">Home</a>

					<a href="#">Pricing</a>

					<a href="#">About</a>

					<a href="#">Contact</a>
				</p>

				<p class="footer-company-name">Chocohut Pvt Limitted © 2015</p>
			</div>

			<div class="footer-center">

				<div>
					<i class="fa fa-map-marker"></i>
					<p><span>444 S. Cedros Ave</span>caltex, Kannur</p>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>1234567890</p>
				</div>

				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:support@company.com">support@chocohut.com</a></p>
				</div>

			</div>

			<div class="footer-right">

				<p class="footer-company-about">
					<span>About the company</span>
					since 2015.chocohut,Incorporated is an American multinational manufacturer of confectionery,and other food products and a provider of chocolate services.

				</p>

				<div class="footer-icons">

					<a href="#"><i class="fa fa-facebook" ></i></a>
					<a href="#"><i class="fa fa-twitter"></i></a>
					<a href="#"><i class="fa fa-linkedin"></i></a>
					<a href="#"><i class="fa fa-github"></i></a>

				</div>

			</div>

		</footer>

chocolate_shop/templates/header.html
{% load static %}

<header>
    <center>
        <a href="#"><img src="{% static 'img/logonew.png' %}" alt="logimage" width="80px" height="80px"></a>
    </center>


</header>

chocolate_shop/templates/home.html
{% load static %}

<html lang="en">
<head>
    <style>
        .ul{font-size:small;
        }
    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="Welcome to Chocohut where you can buys different items....">
    <title>See Our Products - Chocohut</title>
</head>
<body>
    <div class="container">
        {% include 'header.html' %}

    </div>
    <div class="container" >
    <nav class="navbar navbar-expand-lg navbar-light bg-light" >
        <div class="container-fluid" >
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent" >
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="#">HOME</a>
                     </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#about">ABOUT</a>
                    </li>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="placeDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                       BRANCHES
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown" >
                          <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kasaragod_district">Kasargod</a>

                          </li>
                          <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kannur_district">Kannur</a>

                          </li>
                          <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kozhikode_district">Kozhikode</a>

                          </li>

                          <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Trissur_district">Trissur</a>

                          </li>
                          <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Palakkad_district">palakkad</a>

                          </li>
                          <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Eranakulam_district">Eranakulam</a>

                          </li>
                          <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram_district">Trivantrum</a>

                          </li>
                    </ul></li>

                    <li class="nav-item" >
                        <a class="nav-link" href="{% url 'chocolate_app:login' %}" style="padding-left:660px;">LOGIN</a>
                    </li>
                     <li class="nav-item" >
                        <a class="nav-link" href="{% url 'chocolate_app:register' %}" >REGISTER</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    </div>
    <div class="container">
        <img src="{% static 'img/banner4.jpg' %}" alt="our products" width="100%" height="400px">
    </div><br>
    <div id="about" class="container">
        <h2>About</h2>
        <p> Buy online organic Bean to bar chocolate in India at Chocohut. This range of chocolates makes by natural and Purest Cacao Bean. Buy wide range of chocolate.To make this all natural chocolate chip bar, we roasted and cracked cacao beans and mixed it through the dark chocolate to give it a crunchy texture.All of these chocolate bars tested negative for cadmium and lead and contain above 70% cacao for maximum health benefits.</p>
    </div><br>
        <div class="col-md-12 text-center" style="padding-top:30px;">

            <a href="{% url 'chocolate_app:login' %}" class="btn btn-dark btn-lg">Shop Here</a>

        </div>
<br>
    {% include 'footer.html' %}
     <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

chocolate_shop/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
<style>
body{
  font-family: Calibri, Helvetica, sans-serif;
}
.container {
    padding: 50px;
    background-color: grey;
    width:300px;
    margin:80px;
}

input[type=text], input[type=password] {
  width: 300px;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}
input[type=text]:focus, input[type=password]:focus {
  outline: none;
}
 div {
            padding: 10px 0;
         }
.registerbtn {
  background-color:  #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 325px;
  opacity: 0.9;
}
.registerbtn:hover {
  opacity: 1;
}

</style>
</head>
<body>
    <form method="post" action="{% url 'chocolate_app:login' %}">
        {% csrf_token %}
        <center>
        <div class="container">
            <h2>login here</h2>
            <input type="text" name="username" placeholder= "Username" size="15" required /><br>
            <input type="password" name="password" placeholder="Password" size="15" required /><br>
            <input type="submit" class="registerbtn" value="Login"><br>
            {% for msg in messages %}
                <h4 style="color:black">{{msg}}</h4>
            {% endfor %}
            <p>Not Registered? please</p><a href="{% url 'chocolate_app:register' %}" > sign up here</a>

        </div>
        </center>
    </form>
</body>
</html>

chocolate_shop/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
<style>
body{
  font-family: Calibri, Helvetica, sans-serif;
}
.container {
    padding: 50px;
    background-color: grey;
    width:300px;
    margin:80px;
}

input[type=text], input[type=password] {
  width: 300px;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}
input[type=text]:focus, input[type=password]:focus {
  outline: none;
}
 div {
            padding: 10px 0;
         }
.registerbtn {
  background-color: #4CAF50;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 125px;
  opacity: 0.9;
}
.registerbtn:hover {
  opacity: 1;
}

</style>
</head>
<body>
    <form method="post" action="{% url 'chocolate_app:register' %}">
        {% csrf_token %}

        <center>
        <div class="container">
            {% for msg in messages %}
                <h4 style="color:black">{{msg}}</h4>
            {% endfor %}
            <h2>Register Here</h2>
            <input type="text" name="username" placeholder= "Username" size="15" required /><br>
            <input type="password" name="password" placeholder="Password" size="15" required /><br>
            <input type="password" name="cpassword" placeholder="Confirm Password" size="15"required /><br>
            <input type="reset" class="registerbtn" value="Reset">
            <input type="submit" class="registerbtn" value="Register"><br>
            <p>Already Registered? please</p><a href="{% url 'chocolate_app:login' %}"> Login</a>
        </div>
        </center>
    </form>
</body>
</html>

chocolate_shop/templates/shop.html
{% load static %}

<html lang="en">
<head>
    <style>
        .ul{font-size:small;
        }
    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="Welcome to Chocohut where you can buys different items....">
    <title>See Our Products - Chocohut</title>
</head>
<body>
    <div class="container">
        {% include 'header.html' %}

    </div>
    <div class="container" >
    <nav class="navbar navbar-expand-lg navbar-light bg-light" >
        <div class="container-fluid" >
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent" >
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Home</a>
                     </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#about">About</a>
                    </li>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="placeDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                       Branches
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown" >
                          <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kasaragod_district">Kasargod</a>

                          </li>
                          <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kannur_district">Kannur</a>

                          </li>
                          <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kozhikode_district">Kozhikode</a>

                          </li>

                          <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Trissur_district">Trissur</a>

                          </li>
                          <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Palakkad_district">palakkad</a>

                          </li>
                          <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Eranakulam_district">Eranakulam</a>

                          </li>
                          <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Thiruvananthapuram_district">Trivantrum</a>

                          </li>
                    </ul> </li>

                    <li class="nav-item" >
                        <a class="nav-link" href="{% url 'chocolate_app:shop' %}" style="padding-left:620px;">{{user.username}}</a>
                    </li>
                     <li class="nav-item" >
                        <a class="nav-link" href="{% url 'chocolate_app:logout' %}" >Logout</a>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
    </div>
    <div class="container">
        <img src="{% static 'images/cbanner.png' %}" alt="our products" width="100%" height="400px">
    </div><br>
    <div id="about" class="container">
        <h2>About</h2>
        <p> Buy online organic Bean to bar chocolate in India at Chocohut. This range of chocolates makes by natural and Purest Cacao Bean. Buy wide range of chocolate.To make this all natural chocolate chip bar, we roasted and cracked cacao beans and mixed it through the dark chocolate to give it a crunchy texture.All of these chocolate bars tested negative for cadmium and lead and contain above 70% cacao for maximum health benefits.</p>
    </div><br>
        <div class="col-md-12 text-center" style="padding-top:30px;">

            <a href="{% url 'chocolate_app:confirm' %}" class="btn btn-dark btn-lg">Chocolate Shopping</a>

        </div>
<br>
    {% include 'footer.html' %}
     <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>